# Generated by Django 5.2.15 on 2026-06-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=30)),
                ('state_changed_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(blank=True, max_length=1, null=True)),
                ('grade_confidence', models.FloatField(blank=True, null=True)),
                ('untouched', models.BooleanField(default=False)),
                ('est_value', models.PositiveIntegerField(blank=True, help_text='₹', null=True)),
                ('arrived_at_facility', models.DateTimeField(blank=True, null=True)),
                ('storage_cost_accrued', models.PositiveIntegerField(default=0, help_text='₹')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=50)),
                ('mrp', models.PositiveIntegerField(help_text='₹')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('attributes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
