# Generated by Django 5.2.15 on 2026-06-13 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_grade', models.CharField(default='B', max_length=1)),
                ('min_recovery_pct', models.PositiveSmallIntegerField(default=60)),
                ('action', models.CharField(choices=[('AUTO_RELIST', 'Auto relist'), ('LIQUIDATE', 'Liquidate'), ('DONATE', 'Donate')], default='AUTO_RELIST', max_length=15)),
                ('active', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
