# Generated by Django 5.2.15 on 2026-06-13 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '__first__'),
        ('marketplace', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.CharField(choices=[('RETURN', 'Return'), ('RESALE', 'Resale'), ('FACILITY', 'Facility intake')], default='RETURN', max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('vlm_provider', models.CharField(blank=True, max_length=30)),
                ('embedding_provider', models.CharField(blank=True, max_length=30)),
                ('vlm_result', models.JSONField(blank=True, default=dict)),
                ('similarity', models.JSONField(blank=True, default=dict)),
                ('metadata_findings', models.JSONField(blank=True, default=dict)),
                ('history_signals', models.JSONField(blank=True, default=dict)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('fraud_score', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('suggested_grade', models.CharField(blank=True, max_length=1)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='marketplace.order')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_assessments', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='catalog.itemunit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=300)),
                ('role', models.CharField(choices=[('UPLOADED', 'Buyer upload'), ('REFERENCE', 'Reference (listed)')], max_length=10)),
                ('client_metadata', models.JSONField(blank=True, default=dict)),
                ('server_metadata', models.JSONField(blank=True, default=dict)),
                ('phash', models.CharField(blank=True, max_length=64)),
                ('embedding_ref', models.CharField(blank=True, max_length=200)),
                ('vlm_notes', models.JSONField(blank=True, default=dict)),
                ('quality', models.FloatField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='grading.gradingassessment')),
            ],
        ),
        migrations.AddIndex(
            model_name='gradingassessment',
            index=models.Index(fields=['unit', 'status'], name='grading_gra_unit_id_87ae78_idx'),
        ),
        migrations.AddIndex(
            model_name='gradingassessment',
            index=models.Index(fields=['status'], name='grading_gra_status_a639c2_idx'),
        ),
        migrations.AddIndex(
            model_name='gradingassessment',
            index=models.Index(fields=['-created_at'], name='grading_gra_created_2af152_idx'),
        ),
        migrations.AddIndex(
            model_name='gradingimage',
            index=models.Index(fields=['assessment', 'role'], name='grading_gra_assessm_1ee1b0_idx'),
        ),
    ]
