# Generated by Django 5.2.15 on 2026-06-13 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product_origin'),
        ('grading', '0001_initial'),
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taste_vector', models.JSONField(blank=True, default=list)),
                ('dim', models.PositiveIntegerField(default=0)),
                ('category_affinity', models.JSONField(blank=True, default=dict)),
                ('brand_affinity', models.JSONField(blank=True, default=dict)),
                ('price_mean', models.FloatField(default=0.0)),
                ('price_std', models.FloatField(default=0.0)),
                ('green_propensity', models.FloatField(default=0.0)),
                ('n_orders', models.PositiveIntegerField(default=0)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demand_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_vector', models.JSONField(blank=True, default=list)),
                ('dim', models.PositiveIntegerField(default=0)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector', to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResaleAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ceiling', models.PositiveIntegerField()),
                ('floor', models.PositiveIntegerField()),
                ('current_price', models.PositiveIntegerField()),
                ('step_pct', models.FloatField()),
                ('interval_seconds', models.PositiveIntegerField()),
                ('tier', models.PositiveIntegerField(default=0)),
                ('max_tier', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('next_step_at', models.DateTimeField(blank=True, null=True)),
                ('pricing', models.JSONField(blank=True, default=dict)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to=settings.AUTH_USER_MODEL)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='marketplace.listing')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resale_auctions', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='catalog.itemunit')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField()),
                ('components', models.JSONField(blank=True, default=dict)),
                ('tier', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SENT', 'Alert sent'), ('VIEWED', 'Viewed'), ('PURCHASED', 'Purchased'), ('EXPIRED', 'Expired')], default='SENT', max_length=10)),
                ('alerted', models.BooleanField(default=False)),
                ('price_at_alert', models.PositiveIntegerField(blank=True, null=True)),
                ('green_credit_bonus', models.PositiveIntegerField(default=0)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resale_matches', to=settings.AUTH_USER_MODEL)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='nextowner.resaleauction')),
            ],
            options={
                'ordering': ['auction_id', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='ResaleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('original_price', models.PositiveIntegerField()),
                ('age_months', models.FloatField(default=0.0)),
                ('linked', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending grading'), ('PRICED', 'Priced & listed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resale_requests', to='grading.gradingassessment')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resale_requests', to='marketplace.listing')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resale_requests', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resale_requests', to='catalog.itemunit')),
            ],
        ),
        migrations.AddIndex(
            model_name='resaleauction',
            index=models.Index(fields=['status', 'next_step_at'], name='nextowner_r_status_7db401_idx'),
        ),
        migrations.AddIndex(
            model_name='resaleauction',
            index=models.Index(fields=['-created_at'], name='nextowner_r_created_6e7231_idx'),
        ),
        migrations.AddIndex(
            model_name='matchedge',
            index=models.Index(fields=['auction', 'tier'], name='nextowner_m_auction_53e407_idx'),
        ),
        migrations.AddIndex(
            model_name='matchedge',
            index=models.Index(fields=['buyer', 'status'], name='nextowner_m_buyer_i_7a95ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchedge',
            constraint=models.UniqueConstraint(fields=('auction', 'buyer'), name='uniq_auction_buyer'),
        ),
        migrations.AddIndex(
            model_name='resalerequest',
            index=models.Index(fields=['unit', 'status'], name='nextowner_r_unit_id_e0b1ee_idx'),
        ),
        migrations.AddIndex(
            model_name='resalerequest',
            index=models.Index(fields=['status'], name='nextowner_r_status_612634_idx'),
        ),
    ]
