# Generated by Django 5.2.15 on 2026-06-13 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=30)),
                ('state_changed_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('NEW', 'New'), ('FACILITY_RELIST', 'Facility relist'), ('USER_RESALE', 'User resale'), ('SELLER_RETURN', 'Seller return relist')], max_length=20)),
                ('price', models.PositiveIntegerField(help_text='₹')),
                ('band_lo', models.PositiveIntegerField(blank=True, null=True)),
                ('band_hi', models.PositiveIntegerField(blank=True, null=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('lister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings_created', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='catalog.itemunit')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=30)),
                ('state_changed_at', models.DateTimeField(auto_now=True)),
                ('return_reason', models.CharField(blank=True, choices=[('DIDNT_MATCH', "Didn't match description"), ('WRONG_SIZE', 'Wrong size / fit'), ('CHANGED_MIND', 'Changed my mind'), ('DEFECTIVE', 'Damaged / defective'), ('OTHER', 'Other')], max_length=20)),
                ('claimed_untouched', models.BooleanField(default=False)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('return_comment', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='marketplace.listing')),
            ],
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['state', 'source'], name='marketplace_state_5f698f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['state'], name='marketplace_state_2766dd_idx'),
        ),
    ]
