# Generated by Django 5.2.15 on 2026-06-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chosen_size',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
